import { createApp } from "vue";
import App from "./App.vue";
const app = createApp(App);
import router from "./router";
import dict from "@lib/plug/dict.js";
import deepTree from "@lib/plug/deepTree.js";
import "@lib/style/index.less";
import installElementPlus from "./plugins/element.js";
installElementPlus(app);
app.use(router);
app.use(dict);
app.use(deepTree);
app.mount("#app");
